#! python3
# tabulate_salmon_qc.py
# Simple script to read in .e files generated by salmon
# and tabulate the results for easy understanding

import os, argparse, re

# Define functions
def validate_args(args):
    # Validate input file locations
    if not os.path.isdir(args.qcDir):
        print('I am unable to locate the parent directory where salmon stderr files are (' + args.qcDir + ')')
        print('Make sure you\'ve typed the file name or location correctly and try again.')
        quit()
    # Validate output file location
    if os.path.isfile(args.outputFileName):
        print('File already exists at output location (' + args.outputFileName + ')')
        print('Make sure you specify a unique file name and try again.')
        quit()

def get_qc_count_from_files(stderrFiles):
    '''
    Parameters:
        stderrFiles -- a list containing strings that point to stderr
                       files containing mapping rate values
    Returns:
        statsTable -- a list of lists with structure like:
                      [
                          [header_row_values],
                          [sample1, mapping_rate],
                          [sample2, mapping_rate],
                          ...
                      ]
    '''
    percentageRegex = re.compile(r"\d{1,3}\.\d{1,4}%")
    
    # Setup the output table format
    statsTable=["sample\tmapping_rate"]
    
    # Parse all logs files
    for file in stderrFiles:
        # Get the sample name from the file prefix
        sampleName = os.path.basename(file).split(".")[0]
        
        # Parse the file
        with open(file, "r") as fileIn:
            for line in fileIn:
                l = line.strip("\r\n ")
                
                # Get the sample name
                if "[ output ] => " in l:
                    sampleName = l.split(" => { ")[1].split(" }")[0]
                    statsTable.append([sampleName])
                
                # Get the mapping rate
                if "Mapping rate =" in l:
                    # Extract information from line and store it
                    mappingRate = l.split(" ")[-1]
                    
                    statsTable[-1] += [mappingRate]
            statsTable[-1] = "\t".join(statsTable[-1])
    
    return statsTable

## Main
def main():
    # User input
    usage = """%(prog)s accepts a directory containing stderr files output from salmon
    and writes a condensed table of mapping statistics to the output file.
    """
    p = argparse.ArgumentParser(description=usage)
    # Required
    p.add_argument("-i", dest="qcDir",
                   required=True,
                   help="Input directory containing salmon stderr files")
    p.add_argument("-o", dest="outputFileName",
                   required=True,
                   help="Output file name for the mapping rate table")
    # Optional
    p.add_argument("--prefix", dest="filePrefix",
                   required=False,
                   help="""Specify the file prefix uniquely identifying
                   salmon stderr files (default == 'salmon.e')""",
                   default="salmon.e")
    
    args = p.parse_args()
    validate_args(args)
    
    # Get chopper stderr files list
    stderrFiles = []
    for file in os.listdir(args.qcDir):
        if file.startswith(args.filePrefix):
            stderrFiles.append(os.path.join(args.qcDir, file))
    
    # Combine salmon stderr files
    statsTable = get_qc_count_from_files(stderrFiles)
    
    # Write output
    with open(args.outputFileName, "w") as fileOut:
        fileOut.write("\n".join(statsTable))
    
    # Alert user to program success
    print("Program completed successfully!")

if __name__ == "__main__":
    main()
